### PR TITLE
update contract

### PR DESCRIPTION
**Pull request by lucky917**
change > to >= to avoid contract mistake when buy with exact money

### CODE REVIEW

**Comment by HackFisher** [comment]
Thanks for join Evolution Land developer reward plan,

For this PR, 10000 RING reward for you, please leave your registered account (email or eth address) on https://www.evolution.land/ here for receiving the RING reward.

**Comment by lucky917** [comment]
thx. My Address is: 0x01e1c239A3B11cd21A1C8E762421EAa5554fAA1C

**Comment by hammeWang** [comment]
@lucky917 open https://www.evolution.land and sign up, then you will see 10000 ring unclaimed in your profile.

**Comment by hammeWang** [comment]
@lucky917 open https://www.evolution.land and sign up, then you will see 10000 ring unclaimed in your profile. leave a message here if you have any problems. Thanks for your contribution.

**Pull request merged**
